### ISSUE TITLE
There is an error :(

### ISSUE THREAD

**Issue by yllekz** [nejdetkadir/freetube#1]
I deployed this container and pasted a URL into the field and hit "Get video" but got ``There is an error :(`` ...No other logs available. Did i do something wrong?

This is my docker-compose:

```
version: '2.1'
services:
  freetube:
    image: nejdetkadirr/freetube:1.0.0
    restart: unless-stopped
    container_name: freetube
    ports:
      - 3000:3000
```
